#!/bin/bash
#SBATCH -p 256GB
#SBATCH -n 64
#SBATCH -t 28-00:00:00
#SBATCH -o test_job.log
#SBATCH -e test_job.err
#SBATCH -J test_job
#SBATCH --mem=250GB

python main.py --input_dir input --target H0208 --name H0208 --output_dir output_1 --n_cpu 48