"""
Extract lDDT scores from pairwise interface analysis results.

This module reads lDDT output files generated by external tools and extracts
the global lDDT scores for each interface pair, organizing them into a result file.
"""

import os
import sys

def get_lddt_scores(model_name, output_dir):
    """
    Extract and save lDDT scores for all pairwise interfaces.
    
    Reads the list of interface pairs and extracts global lDDT scores from
    the corresponding lDDT output files. Writes results for both original
    and reversed chain pair orders to ensure complete coverage.
    
    Args:
        model_name: Model name
        output_dir: Path to output directory (will use output_dir/model_name/)
    """
    model_output_dir = os.path.join(output_dir, model_name)
    interface_tmp_dir = os.path.join(model_output_dir, 'interface_tmp')
    pairwise_lddt_dir = os.path.join(interface_tmp_dir, 'pairwise_interfaces_for_lddt')
    
    fp = open(os.path.join(interface_tmp_dir, 'pairwise_interfaces_for_lddt.list'), 'r')
    cases = []
    for line in fp:
        words = line.split()
        model = words[0]
        pair1 = words[1]
        pair2 = words[2]
        cases.append([model, pair1, pair2])
    fp.close()

    rp = open(os.path.join(model_output_dir, model_name + '.lddt'), 'w')
    for case in cases:
        model = case[0]
        pair1 = case[1]
        prot1A = pair1.split('-')[0]
        prot1B = pair1.split('-')[1]
        newpair1 = prot1B + ':' + prot1A
        pair2 = case[2]
        prot2A = pair2.split('-')[0]
        prot2B = pair2.split('-')[1]
        newpair2 = prot2B + ':' + prot2A

        lddt = ''
        lddt_file = os.path.join(pairwise_lddt_dir, f'{pair1}_{pair2}.lddt')
        if os.path.exists(lddt_file):
            fp = open(lddt_file, 'r')
            for line in fp:
                words = line.split()
                if len(words) >= 4:
                    if words[0] == 'Global' and words[1] == 'LDDT' and words[2] == 'score:':
                        lddt = words[3]
                        break

            fp.close()
        if lddt:
            rp.write(model + '\t' + pair1.replace('-',':') + '\t' + pair2.replace('-',':') + '\t' + lddt + '\n')
            rp.write(model + '\t' + newpair1 + '\t' + newpair2 + '\t' + lddt + '\n')
        else:
            print(model_name, model, pair1, pair2)
    rp.close()

# if __name__ == "__main__":
#     target = sys.argv[1]
#     output_dir = sys.argv[2]
#     get_lddt_scores(target, output_dir)