"""
Extract TM-score from pairwise interface analysis results.

This module reads TMscore output files generated by external tools and extracts
the TM-score values for each interface pair, organizing them into a result file.
"""

import os
import sys

def get_tm_scores(model_name, output_dir):
    """
    Extract and save TM-scores for all pairwise interfaces.
    
    Reads the list of interface pairs and extracts TM-score values from
    the corresponding TMscore output files. Writes results for both original
    and reversed chain pair orders to ensure complete coverage.
    
    Args:
        model_name: Model name
        output_dir: Path to output directory (will use output_dir/model_name/)
    """
    model_output_dir = os.path.join(output_dir, model_name)
    interface_tmp_dir = os.path.join(model_output_dir, 'interface_tmp')
    pairwise_dir = os.path.join(interface_tmp_dir, 'pairwise_interfaces')
    
    fp = open(os.path.join(interface_tmp_dir, 'pairwise_interfaces.list'), 'r')
    cases = []
    for line in fp:
        words = line.split()
        model = words[0]
        pair1 = words[1]
        pair2 = words[2]
        cases.append([model, pair1, pair2])
    fp.close()
    
    rp = open(os.path.join(model_output_dir, model_name + '.tm'), 'w')
    for case in cases:
        model = case[0]
        pair1 = case[1]
        prot1A = pair1.split('-')[0]
        prot1B = pair1.split('-')[1]
        newpair1 = prot1B + ':' + prot1A
        pair2 = case[2]
        prot2A = pair2.split('-')[0]
        prot2B = pair2.split('-')[1]
        newpair2 = prot2B + ':' + prot2A

        tm = ''
        tm_file = os.path.join(pairwise_dir, f'{pair1}_{pair2}.tm')
        if os.path.exists(tm_file):
            fp = open(tm_file, 'r')
            for line in fp:
                words = line.split()
                if len(words) > 3:
                    if words[0] == 'TM-score' and words[1] == '=':
                        tm = words[2]
                        break
            fp.close()
        if tm:
            rp.write(model + '\t' + pair1.replace('-',':') + '\t' + pair2.replace('-',':') + '\t' + tm + '\n')
            rp.write(model + '\t' + newpair1 + '\t' + newpair2 + '\t' + tm + '\n')
        else:
            print(model_name, model, pair1, pair2)
    rp.close()

# if __name__ == "__main__":
#     target = sys.argv[1]
#     output_dir = sys.argv[2]
#     get_tm_scores(target, output_dir)