"""
Extract DockQ scores from pairwise interface analysis results.

This module reads DockQ output files generated by external tools and extracts
the total DockQ scores for each interface pair, organizing them into a result file.
"""

import os
import sys

def get_dockq_scores(model_name, output_dir):
    """
    Extract and save DockQ scores for all pairwise interfaces.
    
    Reads the list of interface pairs and extracts total DockQ scores from
    the corresponding DockQ output files. Writes results for both original
    and reversed chain pair orders. Missing scores are recorded as 0.0.
    
    Args:
        model_name: Model name
        output_dir: Path to output directory (will use output_dir/model_name/)
    """
    model_output_dir = os.path.join(output_dir, model_name)
    interface_tmp_dir = os.path.join(model_output_dir, 'interface_tmp')
    pairwise_dir = os.path.join(interface_tmp_dir, 'pairwise_interfaces')
    
    fp = open(os.path.join(interface_tmp_dir, 'pairwise_interfaces.list'), 'r')
    cases = []
    for line in fp:
        words = line.split()
        model = words[0]
        category = words[1]
        pair1 = words[2]
        pair2 = words[3]
        cases.append([model, category, pair1, pair2])
    fp.close()
    
    rp = open(os.path.join(model_output_dir, model_name + '.dockq'), 'w')
    for case in cases:
        model = case[0]
        category = case[1]
        pair1 = case[2]
        prot1A = pair1.split('-')[0]
        prot1B = pair1.split('-')[1]
        newpair1 = prot1B + ':' + prot1A
        pair2 = case[3]
        prot2A = pair2.split('-')[0]
        prot2B = pair2.split('-')[1]
        newpair2 = prot2B + ':' + prot2A

        dockq = ''
        dockq_file = os.path.join(pairwise_dir, f'{pair1}_{pair2}.dockq')
        if os.path.exists(dockq_file):
            fp = open(dockq_file, 'r')
            for line in fp:
                if line[0] == '*':
                    pass
                else:
                    words = line.split()
                    if len(words) > 7:
                        if words[0] == 'Total' and words[1] == 'DockQ' and words[2] == 'over':
                            dockq = words[6]
                            break
            fp.close()
        if dockq:
            rp.write(model + '\t' + category + '\t' + pair1.replace('-',':') + '\t' + pair2.replace('-',':') + '\t' + dockq + '\n')
            rp.write(model + '\t' + category + '\t' + newpair1 + '\t' + newpair2 + '\t' + dockq + '\n')
        else:
            rp.write(model + '\t' + category + '\t' + pair1.replace('-',':') + '\t' + pair2.replace('-',':') + '\t0.0\n')
            rp.write(model + '\t' + category + '\t' + newpair1 + '\t' + newpair2 + '\t0.0\n')
            print(model_name, model, pair1, pair2)
    rp.close()

# if __name__ == "__main__":
#     target = sys.argv[1]
#     output_dir = sys.argv[2]
#     get_dockq_scores(target, output_dir)